//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Competitiveness
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompetitivenessIndexEntities : DbContext
    {
        public CompetitivenessIndexEntities()
            : base("name=CompetitivenessIndexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attributes> Attributes { get; set; }
        public virtual DbSet<AttributesOfCompany> AttributesOfCompany { get; set; }
        public virtual DbSet<Branchs> Branchs { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Criterias> Criterias { get; set; }
        public virtual DbSet<CriteriasOfCompany> CriteriasOfCompany { get; set; }
        public virtual DbSet<Factors> Factors { get; set; }
        public virtual DbSet<FactorsOfCompany> FactorsOfCompany { get; set; }
    }
}
