//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Competitiveness
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompetitivenessIndexEntities : DbContext
    {
        public CompetitivenessIndexEntities()
            : base("name=CompetitivenessIndexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<AttributesOfCompany> AttributesOfCompanies { get; set; }
        public virtual DbSet<Branch> Branchs { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Criteria> Criterias { get; set; }
        public virtual DbSet<CriteriasOfCompany> CriteriasOfCompanies { get; set; }
        public virtual DbSet<Factor> Factors { get; set; }
        public virtual DbSet<FactorsOfCompany> FactorsOfCompanies { get; set; }
    }
}
